app/account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from account.views import LoginView, RegisterView

app_name = "account"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path(
        "login/",
        LoginView.as_view(),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
]

app/config/urls.py
from config.settings import MEDIA_ROOT, MEDIA_URL
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("news/", include("news.urls")),
    path("account/", include("account.urls")),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

app/core/urls.py
from django.urls import include, path
from django.views.generic import TemplateView

app_name = "core"

urlpatterns = [
    path(
        "features/",
        TemplateView.as_view(template_name="features.html"),
        name="features",
    ),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
]

app/news/urls.py
from django.urls import path

from news.views import NewsListView

app_name = "news"

urlpatterns = [
    path("", NewsListView.as_view(), name="list"),
]

app/account/models.py
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)
from django.db.models import BooleanField, EmailField
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must be assigned to is_staff=True")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must be assigned to is_superuser=True")
        if extra_fields.get("is_active") is not True:
            raise ValueError("Superuser must be assigned to is_active=True")

        return self.create_user(email, password, **extra_fields)

    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError(_("User must have email"))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = EmailField(unique=True, null=True)
    is_active = BooleanField(default=False)
    is_staff = BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

app/news/models.py
from django.db.models import CharField, DateTimeField, ImageField, Model, TextField


class News(Model):
    title = CharField(max_length=128, verbose_name="Заголовок")
    text = TextField(verbose_name="Основной текст")
    image = ImageField(
        verbose_name="Изображение", upload_to="news/", blank=True, null=True
    )
    created = DateTimeField(auto_now_add=True, verbose_name="Дата создания")

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"

        ordering = [
            "-created",
        ]

    def __str__(self):
        return self.title

app/account/forms.py
from django.forms import (
    CharField,
    EmailField,
    ModelForm,
    PasswordInput,
    TextInput,
    ValidationError,
)

from account.models import User


class RegistrationForm(ModelForm):
    email = EmailField(
        label="Введите e-mail",
        help_text="Необходим e-mail",
        error_messages={"required": "Необходим e-mail"},
    )
    password = CharField(
        label="Создайте пароль",
        widget=PasswordInput,
        error_messages={"required": "Необходим пароль"},
    )

    class Meta:
        model = User
        fields = ("email",)

    def save(self):
        user = super(RegistrationForm, self).save()
        user.is_active = True
        user.email = self.cleaned_data["email"]
        user.set_password(self.cleaned_data["password"])
        user.save()

    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise ValidationError("Такой e-mail уже зарегистрирован")
        return email


class LoginForm(ModelForm):
    email = EmailField(widget=TextInput)
    password = CharField(widget=PasswordInput)

    class Meta:
        model = User
        fields = ("password",)

    def clean_email(self):
        email = self.cleaned_data["email"]
        if not User.objects.filter(email=email):
            raise ValidationError("Аккаунта с таким e-mail не существует")
        return email

app/account/views.py
from account.forms import LoginForm, RegistrationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.edit import FormView


class RegisterView(FormView):
    template_name = "index.html"
    form_class = RegistrationForm
    success_url = reverse_lazy("core:index")

    def form_valid(self, form):
        form.save()
        return super(RegisterView, self).form_valid(form)


class LoginView(FormView):
    template_name = "index.html"
    form_class = LoginForm
    success_url = reverse_lazy("core:index")

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(email=email, password=password)
        if user is None or not user.is_active:
            messages.error(self.request, "Неверный пароль")
            return self.form_invalid(form)
        login(self.request, user)
        return redirect(self.success_url)

app/news/views.py
from django.views.generic import ListView
from news.models import News
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


class NewsListView(LoginRequiredMixin, ListView):
    model = News
    context_object_name = "news"
    paginate_by = 2
    login_url = reverse_lazy("account:login")

app/templates/features.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
  <title>Science Courses</title>
</head>

<body>
  <header class="features-header">
    <div class="container">
      <div class="header__content">
        <p class="logo">Logo</p>

        <nav class="nav">
          <ul class="nav__list">
            <li class="nav__item">
              <a href="{% url 'core:index' %}" class="nav__link">Home</a>
            </li>
            <li class="nav__item">
              <a href="" class="nav__link nav__link-active">Features</a>
            </li>
            <li class="nav__item">
              <a href="" class="nav__link">About</a>
            </li>
            <li class="nav__item">
              <a href="{% url 'core:index' %}" class="nav__link">News</a>
            </li>
          </ul>
        </nav>

        <button class="btn">Start Learn</button>
      </div>
    </div>
  </header>

  <main class="main-features">
    <div class="container feat-container">
      <div class="feat__content">
        <h1 class="feat__title"> Course Of <br /> Astrobiology✨</h1>
        <div class="feat__content-flex">
          <p class="feat__description">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas molestias
            perferendis officia excepturi quibusdam illo facere explicabo, ipsum quaerat sequi veritatis maxime aliquid
            sed est ut, aut amet dolore minima pariatur atque. Distinctio quam earum neque eligendi, odit nobis beatae.
          </p>
          <img src="{% static '/img/features-1.jpg' %}" class="feat-img" alt="astrobiology image">
          <p class="feat__authors">
            Authors: <br />
            Jhon Bernal <br />
            Carl Sagan <br />
            Stephen Hawking <br />
            Kip Thorne <br />
          </p>
        </div>
        <div class="feat__buttons">
          <button class="btn">Explore Now</button>
          <button class="btn-outline">Read <br /> Description</button>
        </div>
      </div>
    </div>
  </main>
</body>

</html>

app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static 'css/index.css' %}" />
  <script src="{% static 'js/index.js' %}" defer></script>
  <title>Science Courses</title>
</head>

<body>

  <header class="header main-header">
    <div class="container">
      <div class="header__content">
        <p class="logo">Logo</p>

        <nav class="nav">
          <ul class="nav__list">
            <li class="nav__item">
              <a href="" class="nav__link nav__link-active">Home</a>
            </li>

            <li class="nav__item">
              <a href="{% url 'core:features' %}" class="nav__link">Features</a>
            </li>

            <li class="nav__item">
              <a href="" class="nav__link">About</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav__item">
              <a href="{% url 'news:list' %}" class="nav__link">News</a>
            </li>
            {% endif %}
          </ul>
        </nav>

        {% if user.is_authenticated %}
        <a href="{% url 'account:logout' %}" class="nav__link">{{ user.email }}</a>
        {% else %}
        <button class="log-link">Login or Register</button>
        {% endif %}

        <button class="btn">Start Learn</button>

      </div>
    </div>
  </header>

  <main class="main">
    <div class="container main-container">
      <div class="content">
        <h1 class="content__title">New Way To Learn Natural Science</h1>
        <p class="content__description">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero
          velit ea asperiores eos minima beatae blanditiis, maiores vel vitae
          facere.
        </p>
        <div class="content__buttons">
          <button class="btn">Show More</button>
          <button class="btn-outline">Get Started</button>
        </div>
      </div>

      <div class="img-block">
        <div class="img__orbe"></div>
        <div class="main__img">
          <img class="img" src="{% static '/img/main.jpg' %}" alt="home image" />
        </div>
      </div>
    </div>
  </main>

  <div class="auth-modal modal display-none">
    <div class="modal-content">
      <span class="modal-close">&times;</span>
      <h2>Login</h2>
      <form method="POST" action="{% url 'account:login' %}">
        {% csrf_token %}
        <label for="auth-email">Email:</label>
        <input type="email" id="auth-email" name="email" required>

        <label for="auth-password">Password:</label>
        <input type="password" id="auth-password" name="password" required>

        <button type="submit" class="btn-signin">Sign in</button>
        <a id="to-register" class="btn-signup">or Register here</a>
      </form>
    </div>
  </div>

  <div class="register-modal modal display-none">
    <div class="modal-content">
      <span class="modal-close">&times;</span>
      <h2>Register</h2>
      <form method="POST" action="{% url 'account:register' %}">
        {% csrf_token %}
        <label for="register-email">Email:</label>
        <input type="email" id="register-email" name="email" required>

        <label for="register-password">Password:</label>
        <input type="password" id="register-password" name="password" required>

        <button type="submit" class="btn-signin">Create an account</button>
        <a id="to-auth" class="btn-signup">or Login here</a>
      </form>
    </div>
  </div>

  <div class="timer-modal display-none">
    <div class="modal-content">
      <span class="timer-close">&times;</span>
      <h2>Science courses are soon started!</h2>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit esse molestiae quod quasi pariatur quidem quo enim porro sunt. Ea labore laborum placeat. Similique animi nihil cum ad autem qui ut dolores illum, molestias assumenda eius quibusdam ratione. Cum, doloribus?</p>
    </div>
  </div>


</body>

</html>

app/templates/news/news_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/index.css' %}" />
  <title>Science Courses</title>
</head>

<body>
  <header class="features-header">
    <div class="container">
      <div class="header__content">
        <p class="logo">Logo</p>

        <nav class="nav">
          <ul class="nav__list">
            <li class="nav__item">
              <a href="{% url 'core:features' %}" class="nav__link">Home</a>
            </li>
            <li class="nav__item">
              <a href="{% url 'news:list' %}" class="nav__link">Features</a>
            </li>
            <li class="nav__item">
              <a href="" class="nav__link">About</a>
            </li>
            <li class="nav__item">
              <a href="" class="nav__link  nav__link-active">News</a>
            </li>
          </ul>
        </nav>

        <button class="btn">Start Learn</button>
      </div>
    </div>
  </header>

  <body>
    <main class="main">
      <div class="container">
        <div class="news-block">
          <h1 class="news__title">Our News</h1>

          <ul class="news">
            {% for item in news %}
            <li class="couple">
              <div class="question">{{ item.title }}
                <img src="{% static 'img/arrow.png' %}" alt="" class="arrow">
              </div>
              <div class="answer">{{ item.text }}
                {% if item.image %}
                <img src="{{ item.image.url }}" alt="" class="answer__img">
                {% endif %}
              </div>
            </li>
            {% endfor %}
        </div>
        <div class="pagination">
          <ul class="step-links">
            {% if page_obj.has_previous %}
            <li class="pagination__arrow pagination__arrow--prev"><a
                href="?{{ request.GET.urlencode }}&page={{ page_obj.previous_page_number }}"></a>
            </li>
            {% if page_obj.number != 2 %}
            <li class="pagination__number"><a href="?{{ request.GET.urlencode }}&page=1">1</a></li>
            {% endif %}
            {% if page_obj.number > 3 %}
            <li><span>...</span></li>
            {% endif %}
            <li class="pagination__number"><a
                href="?{{ request.GET.urlencode }}&page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
            </li>
            {% endif %}
            <li class="pagination__number active"><span>{{ page_obj.number }}</span></li>
            {% if page_obj.has_next %}
            <li class="pagination__number"><a
                href="?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number}}</a>
            </li>
            {% if page_obj.number < page_obj.paginator.num_pages|add:-2 %}
            <li><span>...</span></li>
            {% endif %}
            {% if page_obj.number != page_obj.paginator.num_pages|add:-1 %}
            <li class="pagination__number"><a
                href="?{{ request.GET.urlencode }}&page={{ page_obj.paginator.num_pages }}">{{page_obj.paginator.num_pages }}</a>
            </li>
            {% endif %}
            <li class="pagination__arrow pagination__arrow--next"><a
                href="?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}"></a>
            </li>
            {% endif %}
          </ul>
        </div>

      </div>
    </main>
    <script src="{% static 'js/index.js' %}"></script>
  </body>

</html>